import { ChecklistItem } from '../types/database'

export const legacyTemplates = {
  caminhao: {
    title: 'Checklist de Liberação - Caminhão',
    sections: [
      { name: 'CABINE', items: [
        'Bucha da suspensão',
        'Batente e dobradiça portas',
        'Borrachas das portas',
        'Palhetas do limpador para-brisa',
        'Maçanetas (internas/externas) e manivela dos vidros',
        'Bancos (motorista e passageiro)',
        'Conjunto de basculamento da cabine',
        'Reservatório e mangueira do limpador de para-brisa',
        'Estado da escada',
        'Estado dos retrovisores',
        'Paralama dianteiro',
      ]},
      { name: 'CHASSI', items: [
        'Trincas no chassi e travessas',
        'Rampa e quinta roda',
        'Suportes de fixação (tq combustível, bateria, tq arla)',
        'Danos paralamas traseiros',
        'Danos e fixação do para barro',
        'Trincas e fixação da boca de lobo',
        'Parafuso de fixação do implemento',
        'Plataformas e suportes dos cones',
      ]},
      { name: 'MOTOR', items: [
        'Radiadores, reservatório de água e intercooler',
        'Tensores de correia, roletes e polias',
        'Mangueiras e abraçadeiras do sist. de arrefecimento',
        'Mangueiras e abraçadeiras do sist. de admissão e intercooler',
        'Regulagem de válvulas do motor e vazamentos (água/diesel/lub)',
        'Coxins do motor',
        'Protetores e fixação do silencioso',
        'Folga no eixo da turbina ou vazamentos',
        'Carcaça do filtro e tubulação de ar',
      ]},
      { name: 'SISTEMA ELÉTRICO', items: [
        'Sinalização traseira e dianteira',
        'Faróis e piscas',
        'Chicotes elétricos',
        'Luzes do painel',
        'Alternador, correia e tensor',
        'Ventilador, correia e tensor',
        'Funcionamento dos vidros',
        'Ar condicionado',
        'Ventilador e distribuição do ar',
        'Funcionamento do limpador de para-brisa',
        'Motor de partida',
      ]},
      { name: 'TRANSMISSÃO', items: [
        'Embreagem (folga/funcionamento)',
        'Caixa de câmbio (vazamentos/ruídos)',
        'Cardans e cruzetas',
        'Acoplamentos e flanges',
        'Diferencial (fixação/vazamentos)',
        'Semieixos e juntas',
        'Suportes e coxins da transmissão',
      ]},
      { name: 'EIXO DIANTEIRO', items: [
        'Rolamentos e cubos',
        'Manga de eixo',
        'Amortecedores',
        'Molas/feixes e fixações',
        'Barra estabilizadora',
        'Barra de direção e terminais',
        'Geometria/folgas de direção',
      ]},
      { name: 'EIXO TRASEIRO', items: [
        'Molas/feixes e fixações',
        'Amortecedores',
        'Braços/estabilizadores',
        'Rolamentos e cubos',
        'Eixo/diferencial (ruídos/vazamentos)',
      ]},
      { name: 'SISTEMA PNEUMÁTICO', items: [
        'Reservatórios de ar',
        'Válvulas e conexões',
        'Mangueiras e flexíveis',
        'Câmaras de freio',
        'Tubulações do sistema',
        'Vazamentos/pressão',
      ]},
      { name: 'DIREÇÃO', items: [
        'Bomba da direção',
        'Caixa de direção',
        'Mangueiras e vazamentos',
        'Folgas no sistema',
        'Alinhamento/funcionamento',
      ]},
    ],
  },
  trator: {
    title: 'Checklist de Liberação - Trator',
    sections: [
      { name: 'SISTEMA DO MOTOR', items: [
        'Correias e polias', 'Tensores', 'Bomba d\'água', 'Turbina', 'Anéis e vedações', 'Bomba injetora',
        'Bicos injetores', 'Mangotes', 'Radiadores', 'Trincas/Desgaste',
      ]},
      { name: 'SISTEMA ELÉTRICO', items: [
        'Alternador', 'Bóia do tanque', 'Buzina', 'Rádio de comunicação', 'Ar condicionado', 'Faróis',
        'Relógios em geral', 'Chicotes elétricos', 'Painel de Instrumentos', 'Bateria',
      ]},
      { name: 'CHASSI E CABINE', items: [
        'Trincas', 'Desgaste', 'Fixação', 'Banco', 'Painel de Instrumentos', 'Alavancas e manoplas', 'Retrovisor',
      ]},
      { name: 'TRANSMISSÃO', items: [
        'Caixa de câmbio', 'Cardans e cruzetas', 'Acoplamentos/Flanges', 'Diferencial (fixação/vazamentos)', 'Semieixos/Juntas', 'Coxins/Suportes',
      ]},
      { name: 'EMBREAGEM', items: [
        'Acionamento', 'Folga', 'Desgaste', 'Vazamentos', 'Ajustes',
      ]},
      { name: 'DIREÇÃO', items: [
        'Bomba da direção', 'Caixa de direção', 'Mangueiras/Vazamentos', 'Barra/Terminais', 'Folgas', 'Alinhamento',
      ]},
      { name: 'EIXO DIANTEIRO', items: [
        'Rolamentos/Cubos', 'Manga de eixo', 'Amortecedores', 'Molas/Feixes e fixações', 'Barra estabilizadora',
      ]},
      { name: 'EIXO TRASEIRO', items: [
        'Molas/Feixes e fixações', 'Amortecedores', 'Braços/Estabilizadores', 'Rolamentos/Cubos', 'Eixo/Diferencial (ruídos/vazamentos)',
      ]},
      { name: 'SISTEMA HIDRÁULICO', items: [
        'Reservatório e filtros', 'Bombas hidráulicas', 'Válvulas/Distribuidores', 'Mangueiras/Flexíveis', 'Abraçadeiras/Conexões', 'Vazamentos/Pressão',
      ]},
      { name: 'SISTEMA DE FREIO', items: [
        'Válvulas/Mangueiras', 'Câmaras de freio', 'Lonas/Pastilhas', 'Discos/Tambores', 'Nível de fluido', 'Reservatório de ar',
      ]},
      { name: 'SISTEMA DE COMBUSTÍVEL', items: [
        'Tanque - Fixação', 'Tanque - Vazamentos', 'Bomba de combustível', 'Linhas/Conexões', 'Filtros', 'Tampa/vedação',
      ]},
      { name: 'SISTEMA DE ARREFECIMENTO', items: [
        'Radiador', 'Ventiladores', 'Mangueiras/Abraçadeiras', 'Reservatório', 'Nível', 'Vazamentos',
      ]},
      { name: 'SISTEMA DE LUBRIFICAÇÃO', items: [
        'Nível de óleo', 'Filtros', 'Linhas/Conexões', 'Pontos de graxa', 'Vazamentos',
      ]},
      { name: 'PNEUS', items: [
        'Altura dos sulcos dos pneus', 'Emparelhamento de duplos', 'Desgaste irregular', 'Efetuar a calibragem dos pneus', 'Parafuso de roda',
      ]},
      { name: 'SUSP. DIANT.', items: [
        'Alinhamento do eixo dianteiro', 'Balança (pino/bucha/mancal/fixação)', 'Feixe de mola', 'Braços tensores',
      ]},
      { name: 'SUSP. TRAS.', items: [
        'Alinhamento do eixo traseiro', 'Balança (pino/bucha/mancal/fixação)', 'Feixe de mola', 'Braços tensores',
      ]},
      { name: 'ESTRUTURA (SISTEMA DE LONAMENTO)', items: [
        'Braço dianteiro', 'Braço traseiro', 'Pinos', 'Rolamentos', 'Lona', 'Mola',
      ]},
      { name: 'ADESIVOS E LACRES', items: [
        'Identificação da frota', 'Adesivos refletivos', 'Lacre da placa traseira',
      ]},
    ],
  },
  colhedora: {
    title: 'Checklist de Liberação - Colhedora',
    sections: [
      { name: 'MOTOR DIESEL', items: [
        'Turbina - Fixação', 'Turbina - Vazamentos', 'Turbina - Funcionamento',
        'Mangueiras/Mangotes - Fixação', 'Mangueiras/Mangotes - Vazamento', 'Mangueiras/Mangotes - Abraçadeiras',
        'Motor - Fixação', 'Motor - Vazamentos', 'Motor - Funcionamento', 'Escapamento - Fixação',
      ]},
      { name: 'SISTEMA ELÉTRICO', items: [
        'Correia do alternador - Alinhamento/Tensão', 'Correia do alternador - Cortes e rachaduras',
        'Bóia do tanque - Fio da bóia', 'Buzina - Funcionamento', 'Rádio de comunicação', 'Computador de Bordo',
        'Alarme de ré', 'Sensor de porta', 'Ar condicionado', 'Faróis', 'Chicotes e conexões',
      ]},
      { name: 'MATERIAL RODANTE', items: [
        'Esteira - Tensionamento', 'Esteira - Desgaste', 'Roletes - Fixação', 'Roletes - Desgaste',
        'Motores hidráulicos - Fixação', 'Motores hidráulicos - Vazamentos', 'Motores hidráulicos - Funcionamento',
        'Sapatas/Roda Motriz - Parafusos', 'Sapatas/Roda Motriz - Proteção', 'Sapatas/Roda Motriz - Desgaste/Trincas',
      ]},
      { name: 'PLATAFORMA / DIVISORES', items: [
        'Divisor de linhas - Fixação', 'Divisor de linhas - Ajustes', 'Guias e placas - Desgaste',
        'Rolos alimentadores - Funcionamento', 'Rolos alimentadores - Vazamentos', 'Coberturas/Proteções',
      ]},
      { name: 'CORTE DE BASE', items: [
        'Conjunto de facas - Fixação', 'Conjunto de facas - Desgaste', 'Altura de corte',
        'Rolamentos/Conjuntos', 'Motores/Transmissão', 'Proteções',
      ]},
      { name: 'CORTE DE PONTAS', items: [
        'Conjunto de facas - Fixação', 'Conjunto de facas - Desgaste', 'Altura/ajuste',
        'Motores/Transmissão', 'Proteções',
      ]},
      { name: 'ALIMENTADOR PRIMÁRIO', items: [
        'Esteira - Tensionamento', 'Esteira - Desgaste', 'Rolos - Fixação', 'Rolos - Desgaste',
        'Motores/Válvulas', 'Guia/Proteções',
      ]},
      { name: 'ALIMENTADOR SECUNDÁRIO', items: [
        'Esteira - Tensionamento', 'Esteira - Desgaste', 'Rolos - Fixação', 'Rolos - Desgaste',
        'Motores/Válvulas', 'Guia/Proteções',
      ]},
      { name: 'LIMPADOR / EXTRATOR', items: [
        'Extrator primário - Pá/desgaste', 'Extrator primário - Fixação',
        'Extrator secundário - Pá/desgaste', 'Extrator secundário - Fixação', 'Motores/Válvulas', 'Proteções',
      ]},
      { name: 'ELEVADOR', items: [
        'Correntes - Tensionamento', 'Correntes - Desgaste', 'Aletas/Pás', 'Trilhos/Guias', 'Motores/Válvulas', 'Proteções',
      ]},
      { name: 'SISTEMA HIDRÁULICO', items: [
        'Reservatório e filtros', 'Bombas hidráulicas', 'Válvulas/Distribuidores', 'Mangueiras/Flexíveis', 'Abraçadeiras/Conexões', 'Vazamentos/Pressão',
      ]},
      { name: 'TRANSMISSÃO HIDROSTÁTICA', items: [
        'Hidrostatic drive - Bombas',
        'Hidrostatic drive - Motores',
        'Acoplamentos/Flanges',
        'Vazamentos',
        'Fixações',
      ]},
      { name: 'CABINE / COMANDOS', items: [
        'Assento/ajustes',
        'Cintos de segurança',
        'Painel/indicadores',
        'Comandos/joysticks',
        'Ar condicionado',
        'Limpeza/visibilidade',
      ]},
      { name: 'CHASSI / ESTRUTURA', items: [
        'Trincas/Desgaste',
        'Soldas/Fixações',
        'Pontos de apoio',
        'Proteções',
        'Plataformas/escadas',
      ]},
      { name: 'PICADOR', items: [
        'Rotores/Facas - Fixação',
        'Rotores/Facas - Desgaste',
        'Balanceamento/ruídos',
        'Rolamentos/Conjuntos',
        'Proteções',
      ]},
      { name: 'DESCARGA', items: [
        'Tubo de descarga - Fixação',
        'Tubo de descarga - Giro/acionamento',
        'Defletor/bica - Ajustes',
        'Cilindros/mangueiras',
        'Proteções',
      ]},
      { name: 'GUIAMENTO / AUTOPILOTO', items: [
        'Guias/antenas',
        'Sensores de linha',
        'Calibração',
        'Funcionamento',
        'Telemetria/GPS',
      ]},
      { name: 'SISTEMA DE COMBUSTÍVEL', items: [
        'Tanque - Fixação',
        'Tanque - Vazamentos',
        'Bomba de combustível',
        'Linhas/Conexões',
        'Filtros',
        'Tampa/vedação',
      ]},
      { name: 'SISTEMA DE ARREFECIMENTO', items: [
        'Radiador',
        'Ventiladores',
        'Mangueiras/Abraçadeiras',
        'Reservatório',
        'Nível',
        'Vazamentos',
      ]},
      { name: 'SISTEMA DE LUBRIFICAÇÃO', items: [
        'Nível de óleo',
        'Filtros',
        'Linhas/Conexões',
        'Pontos de graxa',
        'Vazamentos',
      ]},
      { name: 'TRANSMISSÃO FINAL', items: [
        'Redutores finais',
        'Fixações',
        'Vazamentos',
        'Níveis',
        'Proteções',
      ]},
      { name: 'SEGURANÇA', items: [
        'Extintor',
        'Alarme de ré',
        'Iluminação',
        'Sinalização',
        'Etiquetas/Avisos',
      ]},
    ],
  },
  plantadora: {
    title: 'Checklist de Reforma/Entressafra - Plantadora de Cana',
    sections: [
      { name: 'PRIMÁRIA', items: [
        'Lavagem geral',
        'Lubrificação geral',
      ]},
      { name: 'ALIMENTADOR DE ADUBO', items: [
        'Verificar vazamento nas mangueiras',
        'Verificar vazamento no motor hidráulico',
      ]},
      { name: 'ALIMENTADOR DE TOLETE', items: [
        'Verificar conjunto mecânico / reparar se necessário',
      ]},
      { name: 'MECÂNICO', items: [
        'Corredor - reparar se necessário',
        'Esteira - reparar se necessário',
        'Plataforma - reparar se necessário',
        'Rolo açamador - reparar se necessário',
        'Tandem - reparar se necessário',
        'Tanque',
      ]},
      { name: 'ELÉTRICA', items: [
        'Verificar câmera da esteira',
        'Verificar câmera da esteira traseira',
        'Verificar câmera do corredor',
        'Verificar conectores das câmeras',
        'Verificar passagem de cabos',
        'Verificar funcionamento do monitor das câmeras',
        'Verificar alimentação do monitor interface',
        'Verificar sensor rotação',
        'Verificar sensores de fim de curso',
        'Reparar tomada elétrica',
      ]},
      { name: 'CALDEIRARIA - ALIMENTADOR DE ADUBO', items: [
        'Verificar desgaste nas engrenagens',
        'Verificar eixo das engrenagens',
        'Verificar suporte do motor',
      ]},
      { name: 'CALDEIRARIA - ALIMENTADOR DE TOLETE', items: [
        'Verificar estrutura/ajustes',
      ]},
      { name: 'CALDEIRARIA - CAIXA DE ADUBO', items: [
        'Estrutura/vedações',
        'Fixações',
      ]},
      { name: 'CALDEIRARIA - CHASSI', items: [
        'Trincas/soldas',
        'Fixações',
        'Nivelamento/estado',
      ]},
      { name: 'CALDEIRARIA - CORREDOR', items: [
        'Estrutura',
        'Proteções/chapas',
      ]},
      { name: 'CALDEIRARIA - ENGATE', items: [
        'Estrutura',
        'Pinos',
        'Folgas',
      ]},
      { name: 'CALDEIRARIA - ESTEIRA', items: [
        'Estrutura',
        'Guias',
        'Proteções',
      ]},
      { name: 'CALDEIRARIA - GERAL', items: [
        'Reparos e reforços gerais',
        'Soldas/chapas',
      ]},
      { name: 'CALDEIRARIA - PLATAFORMA', items: [
        'Estrutura',
        'Fixações',
      ]},
      { name: 'CALDEIRARIA - ROLO DESTROÇADOR', items: [
        'Estrutura',
        'Rolamentos',
        'Fixações',
      ]},
      { name: 'CALDEIRARIA - TANDEM', items: [
        'Estrutura',
        'Fixações',
        'Rolamentos',
      ]},
      { name: 'PNEUS', items: [
        'Calibragem',
        'Medição de sulco',
      ]},
      { name: 'FUNILARIA', items: [
        'Adesivar',
        'Pintura',
      ]},
    ],
  },
  distribuidora: {
    title: 'Checklist de Reforma/Entressafra - Distribuidora de Cana',
    sections: [
      { name: 'PRIMÁRIA', items: [
        'Lavagem geral',
        'Lubrificação geral',
        'Tandem',
      ]},
      { name: 'MECÂNICO', items: [
        'Hidráulico',
        'Inspeção',
        'Reparar se necessário',
        'Tandem - reparar se necessário',
      ]},
      { name: 'ELÉTRICA', items: [
        'Revisar painel instrumentos/câmera',
        'Revisar tomadas/pinos',
        'Verificar chicotes elétricos',
        'Verificar sinalizações e iluminação',
        'Revisar câmera - reparar se necessário',
      ]},
      { name: 'CALDEIRARIA', items: [
        'Cabeçalho - reparar se necessário',
      ]},
      { name: 'PNEUS', items: [
        'Calibragem',
        'Medição de sulco',
        'Conferir parafusos e porcas',
        'Reparar rodas',
        'Revisar eixo/mancal',
        'Reparar válvula',
        'Balanceamento',
      ]},
      { name: 'FUNILARIA', items: [
        'Pintura',
        'Número/frota e logotipo',
      ]},
    ],
  },
  tortao: {
    title: 'Checklist de Reforma/Entressafra - Tortão',
    sections: [
      { name: 'PRIMÁRIA', items: [
        'Lavagem geral',
        'Lubrificação geral',
      ]},
      { name: 'MECÂNICO', items: [
        'Cesto - reparar se necessário',
        'Hidráulico',
        'Inspeção',
        'Tandem - reparar se necessário',
      ]},
      { name: 'CALDEIRARIA', items: [
        'Cesto - reparar se necessário',
        'Cabeçalho - reparar se necessário',
      ]},
      { name: 'PNEUS', items: [
        'Calibrar pneus e medir sulco',
        'Colocar tampa de válvula',
        'Conferir parafusos e porcas',
        'Fazer rodízio',
        'Inventariar equipamento',
        'Reapertar rodas',
      ]},
      { name: 'FUNILARIA', items: [
        'Pintura/Número frota e logotipo',
      ]},
    ],
  },
  cobridores: {
    title: 'Checklist de Reforma/Entressafra - Cobridores',
    sections: [
      { name: 'TIPO DE SERVIÇO', items: [
        'Trocar buchas e braços',
        'Trocar discos de corte',
        'Montagem',
        'Revisar tanques, suportes e fixações; reparar se necessário',
        'Corrigir trincas',
        'Catalogar peças',
      ]},
    ],
  },
  trailer: {
    title: 'Checklist de Liberação - Reboque/Semi-reboque',
    sections: [
      { name: 'CHASSI', items: [
        'Nivelamento, estado e solda do chassi',
        'Suporte da placa',
        'Suporte da corrente',
        'Suporte do documento',
        'Trincas geral',
        'Trincas mesa 5° roda',
        'Viga frontal / traseira',
        'Vigas laterais',
        'Mancais de basculamento',
        'Pino rei',
      ]},
      { name: 'ELÉTRICO', items: [
        'Chicote elétrico',
        'Iluminação traseira',
        'Iluminação lateral (esquerdo e direito)',
        'Funcionamento e limpeza das conexões',
      ]},
      { name: 'FREIO', items: [
        'Freio pneumático (válvula, mangueiras)',
        'Flexíveis e câmaras de freio',
        'Desgastes da lona de freio',
        'Sistema de freio',
        'Reservatório de ar',
      ]},
    ],
  },
  transbordo: {
    title: 'Checklist de Reforma/Entressafra - Transbordo de Cana',
    sections: [
      { name: 'PRIMÁRIA', items: [
        'Lavagem geral',
        'Lubrificação geral',
      ]},
      { name: 'MECÂNICO', items: [
        'Desmontar cubos de roda',
        'Desmontar tandem',
        'Verificar tandem - rolamentos',
        'Suspensão - pinos/buchas',
        'Eixos/mancais',
        'Conferir parafusos e porcas',
      ]},
      { name: 'HIDRÁULICO', items: [
        'Reservatório e filtros',
        'Bombas hidráulicas',
        'Válvulas/Distribuidores',
        'Mangueiras/Flexíveis',
        'Abraçadeiras/Conexões',
        'Vazamentos/Pressão',
      ]},
      { name: 'ELÉTRICA', items: [
        'Chicotes elétricos',
        'Iluminação traseira',
        'Iluminação lateral',
        'Tomadas/Pinos',
        'Painel/Monitoramento',
      ]},
      { name: 'CALDEIRARIA', items: [
        'Chassi/Estrutura',
        'Soldas/Chapas',
        'Proteções',
        'Mancais de basculamento',
        'Engate',
      ]},
      { name: 'FREIO', items: [
        'Válvulas/Mangueiras',
        'Flexíveis/Câmaras',
        'Lonas/Pastilhas',
        'Reservatório de ar',
      ]},
      { name: 'PNEUS', items: [
        'Calibragem',
        'Medição de sulco',
        'Emparelhamento',
        'Balanceamento',
      ]},
      { name: 'FUNILARIA', items: [
        'Pintura',
        'Número/frota e adesivos',
      ]},
    ],
  },
  motobombas: {
    title: 'Checklist de Reforma/Entressafra - Motobombas',
    sections: [
      { name: 'TIPO DE SERVIÇO', items: [
        'Verificar tanque',
        'Verificar cinta do tanque - reparar se necessário',
        'Verificar entrada de ar no sistema',
        'Verificar lava radiador',
        'Verificar vazamento no radiador',
        'Verificar bomba de centrífuga',
        'Verificar gaxeta',
        'Verificar buchas e folga na chaveta',
        'Verificar parafusos e trincas da caixa e sucção',
        'Verificar vazamentos no motor',
        'Verificar vazamento na bomba motor',
        'Verificar altura dos pneus',
        'Realizar manutenção primária',
        'Verificar eixos e folga do cabeçalho',
        'Verificar guincho de levante do mangote',
        'Verificar cabo de aço e catraca do guincho',
        'Verificar medidor de pressão de óleo do motor',
        'Verificar relógio hidrômetro do motor',
        'Verificar relógio amperímetro da parte elétrica',
        'Verificar relógio de temperatura do motor',
        'Verificar vela eletrônica',
        'Verificar altura dos pneus',
        'Realizar inventário de peças',
        'Verificar pino de freio',
        'Verificar partes móveis pintura e proteção',
        'Verificar mangueira e proteções laterais',
        'Revisar montador',
        'Revisar motor de partida',
        'Revisar chicote da bateria, suporte e fixação',
        'Revisar horímetro',
        'Revisar painel de instrumentos',
        'Teste de sensores',
        'Verificar entrada de ar no mangote de sucção',
        'Verificar abraçadeiras do mangote de sucção',
        'Verificar trincas no cano de saída inox',
        'Verificar válvula de saída',
        'Verificar folga nos cubos',
        'Verificar retentores com vazamento',
        'Verificar embuchamento',
        'Verificar parafusos da roda',
        'Verificar folgas na roda',
      ]},
    ],
  },
  hidroroll: {
    title: 'Checklist de Reforma/Entressafra - Hidro Roll',
    sections: [
      { name: 'TIPO DE SERVIÇO', items: [
        'Verificar pinos e folga do cabeçalho',
        'Verificar rala de giro',
        'Verificar parafusos da rala',
        'Verificar suporte e pino do giro',
        'Verificar estrutura do chassi',
        'Verificar desgaste e trincas da cremalheira',
        'Verificar folga no pino de recuo',
        'Verificar folga das alavancas da marcha',
        'Verificar funcionamento do farol de sinalização',
        'Verificar instalação do by pass',
        'Verificar painel de instrumentos e operação',
        'Verificar giroflex',
        'Verificar faróis (sinalizações e iluminação)',
        'Revisar alternador e baterias',
        'Verificar carenagens',
        'Verificar rolamentos',
        'Verificar desgaste da chaveta do guia',
        'Verificar desgaste da rosca do guia',
        'Verificar regular, limpar e lubrificar corrente do guia',
        'Verificar cavalete de desarme',
        'Verificar limpeza da sapata da ancoragem',
        'Verificar trocar juntas e abraçadeiras',
        'Verificar aspersor',
        'Verificar caixa do painel',
        'Verificar funcionamento do painel',
        'Verificar proteção dos cabos do painel',
        'Verificar sensores',
        'Verificar suspiro de óleo do redutor',
        'Verificar vazamento no retentor do redutor',
        'Verificar folga no eixo do redutor',
        'Verificar sistema de freio do redutor',
        'Verificar redutor e corrente do guia',
        'Verificar fixação do moto redutor',
        'Verificar válvula do moto redutor',
        'Verificar partes móveis pintura e proteção',
        'Verificar pino de freio',
        'Verificar selo mecânico da turbina',
        'Verificar correia, esticador e polia da turbina',
        'Verificar vazamentos nas mangueiras',
        'Verificar sistema by pass',
        'Verificar regular e limpar rolo do guia da mangueira',
        'Verificar cubos do redutor',
        'Verificar parafusos do cubo',
        'Reapertar rodas',
        'Conferir parafusos e porcas',
        'Colocar tampa de válvula',
        'Calibrar pneus e medir sulco',
        'Inventariar pneus equipamento',
        'Desmontar, lavar peças, examinar, engraxar e montar (cubos de roda)',
      ]},
    ],
  },
}

export function buildLegacyItems(templateKey: keyof typeof legacyTemplates): ChecklistItem[] {
  const tpl = legacyTemplates[templateKey]
  const opts = ['OK','Não OK','Não Aplica']
  const items: ChecklistItem[] = []
  let ordem = 1
  tpl.sections.forEach(sec => {
    sec.items.forEach(desc => {
      items.push({
        id: crypto.randomUUID(),
        descricao: `${sec.name} • ${desc}`,
        tipo: 'opcoes',
        obrigatorio: true,
        ordem: ordem++,
        opcoes: opts,
      })
    })
  })
  return items
}
