export const tanquesData = [
  { frota: '6290', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6232', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6250', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6177', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6248', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6231', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6169', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6659', descricao: 'Semirreboque Sergomel' },
  { frota: '6653', descricao: 'Semirreboque Sergomel' },
  { frota: '6228', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6238', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '5615', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6170', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '5609', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6654', descricao: 'Semirreboque Sergomel' },
  { frota: '6215', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6229', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6172', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6249', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6236', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6175', descricao: 'Semirreboque Tanque Edra' },
  { frota: '6216', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6660', descricao: 'Reboque Tanque Sergomel' },
  { frota: '6655', descricao: 'Reboque Tanque Sergomel' },
  { frota: '6178', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6176', descricao: 'Reboque Tanque Rodofort' },
  { frota: '5616', descricao: 'Reboque Tanque Rodofort' },
  { frota: '5624', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6235', descricao: 'Reboque Tanque Rodofort' },
  { frota: '6652', descricao: 'Reboque Tanque Sergomel' },
  { frota: '6171', descricao: 'Reboque Tanque Rodofort' },
  { frota: '5613', descricao: 'Semirreboque Tanque Rodofort' },
  { frota: '6689', descricao: 'Semirreboque Tanque Sergomel' },
  { frota: '6691', descricao: 'Semirreboque Tanque Sergomel' },
  { frota: '6693', descricao: 'Semirreboque Tanque Sergomel' },
  { frota: '6695', descricao: 'Semirreboque Tanque Sergomel' },
  { frota: '6690', descricao: 'Reboque Tanque Sergomel' },
  { frota: '6692', descricao: 'Reboque Tanque Sergomel' },
  { frota: '6694', descricao: 'Reboque Tanque Sergomel' },
  { frota: '6696', descricao: 'Reboque Tanque Sergomel' }
]
